# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple Example Parser
#'
#' This example is adapted from the upstream documentation and simply prints
#' an existing TOML file to standard output.
#'
#' @param filename An existing TOML file
#' @return An integer indicating suggess or failure
#' @examples
#' file <- system.file("toml", "example.toml", package="RcppTomlPlusPlus")
#' simpleParser(file)
simpleParser <- function(filename) {
    .Call(`_RcppTomlPlusPlus_simpleParser`, filename)
}

