# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse a TOML file
#'
#' @param input [character] TOML input, either as chracter value or path to TOML file
#' @param verbose [logical] Optional verbosity flag, no current effect
#' @param fromfile [logical] Optional with default value \sQuote{TRUE} indicating parsing from file
#' @param includize [logical] Optional legacy option, no current effect
#' @param escape [logical] Optiona legacy option, no current effect
#' @return A List with the parsed content
tomlparseImpl <- function(input, verbose = FALSE, fromfile = TRUE, includize = FALSE, escape = TRUE) {
    .Call(`_RcppTomlPlusPlus_tomlparseImpl`, input, verbose, fromfile, includize, escape)
}

foo <- function() {
    invisible(.Call(`_RcppTomlPlusPlus_foo`))
}

foo2 <- function() {
    invisible(.Call(`_RcppTomlPlusPlus_foo2`))
}

#' Simple Example Parser
#'
#' This example is adapted from the upstream documentation and simply prints
#' an existing TOML file to standard output.
#'
#' @param filename An existing TOML file
#' @return An integer indicating suggess or failure
#' @examples
#' file <- system.file("toml", "example.toml", package="RcppTomlPlusPlus")
#' simpleParser(file)
simpleParser <- function(filename) {
    .Call(`_RcppTomlPlusPlus_simpleParser`, filename)
}

